
public class Quetio1 {

public static void main(String[] args) {
	
	
	
	System.out.println("1. Java Basic Programs (1–20)\r\n"
			+ "\r\n"
			+ "Write a Java program to print “Hello World”.\r\n"
			+ "\r\n"
			+ "Write a program to swap two numbers without using a third variable.\r\n"
			+ "\r\n"
			+ "Write a program to check whether a number is even or odd.\r\n"
			+ "\r\n"
			+ "Write a program to find the largest of three numbers.\r\n"
			+ "\r\n"
			+ "Write a program to calculate factorial of a number.\r\n"
			+ "\r\n"
			+ "Write a program to generate Fibonacci series.\r\n"
			+ "\r\n"
			+ "Write a program to check whether a number is prime.\r\n"
			+ "\r\n"
			+ "Write a program to reverse a number.\r\n"
			+ "\r\n"
			+ "Write a program to check whether a number is palindrome.\r\n"
			+ "\r\n"
			+ "Write a program to count digits in a number.\r\n"
			+ "\r\n"
			+ "Write a program to find sum of digits.\r\n"
			+ "\r\n"
			+ "Write a program to print multiplication table.\r\n"
			+ "\r\n"
			+ "Write a program to calculate power of a number.\r\n"
			+ "\r\n"
			+ "Write a program to check Armstrong number.\r\n"
			+ "\r\n"
			+ "Write a program to find GCD of two numbers.\r\n"
			+ "\r\n"
			+ "Write a program to find LCM of two numbers.\r\n"
			+ "\r\n"
			+ "Write a program to print numbers from 1 to N.\r\n"
			+ "\r\n"
			+ "Write a program to find sum of first N natural numbers.\r\n"
			+ "\r\n"
			+ "Write a program to check perfect number.\r\n"
			+ "\r\n"
			+ "Write a program to print ASCII value of a character.\r\n"
			+ "\r\n"
			+ "2. Pattern Printing (21–40)\r\n"
			+ "\r\n"
			+ "Print star triangle pattern.\r\n"
			+ "\r\n"
			+ "Print inverted triangle pattern.\r\n"
			+ "\r\n"
			+ "Print pyramid star pattern.\r\n"
			+ "\r\n"
			+ "Print diamond pattern.\r\n"
			+ "\r\n"
			+ "Print Floyd’s triangle.\r\n"
			+ "\r\n"
			+ "Print number pyramid.\r\n"
			+ "\r\n"
			+ "Print Pascal triangle.\r\n"
			+ "\r\n"
			+ "Print hollow square pattern.\r\n"
			+ "\r\n"
			+ "Print hollow pyramid pattern.\r\n"
			+ "\r\n"
			+ "Print right aligned triangle.\r\n"
			+ "\r\n"
			+ "Print number increasing pattern.\r\n"
			+ "\r\n"
			+ "Print decreasing number pattern.\r\n"
			+ "\r\n"
			+ "Print binary pattern.\r\n"
			+ "\r\n"
			+ "Print alphabet triangle pattern.\r\n"
			+ "\r\n"
			+ "Print hollow diamond pattern.\r\n"
			+ "\r\n"
			+ "Print hourglass pattern.\r\n"
			+ "\r\n"
			+ "Print cross pattern using stars.\r\n"
			+ "\r\n"
			+ "Print zigzag pattern.\r\n"
			+ "\r\n"
			+ "Print hollow rectangle.\r\n"
			+ "\r\n"
			+ "Print spiral star pattern.\r\n"
			+ "\r\n"
			+ "3. String Problems (41–80)\r\n"
			+ "\r\n"
			+ "Reverse a string.\r\n"
			+ "\r\n"
			+ "Check if string is palindrome.\r\n"
			+ "\r\n"
			+ "Count vowels and consonants.\r\n"
			+ "\r\n"
			+ "Count words in a sentence.\r\n"
			+ "\r\n"
			+ "Remove duplicate characters.\r\n"
			+ "\r\n"
			+ "Find first non-repeating character.\r\n"
			+ "\r\n"
			+ "Find first repeating character.\r\n"
			+ "\r\n"
			+ "Check if two strings are anagrams.\r\n"
			+ "\r\n"
			+ "Convert string to uppercase without built-in method.\r\n"
			+ "\r\n"
			+ "Convert string to lowercase without built-in method.\r\n"
			+ "\r\n"
			+ "Remove spaces from string.\r\n"
			+ "\r\n"
			+ "Replace spaces with special character.\r\n"
			+ "\r\n"
			+ "Find longest word in sentence.\r\n"
			+ "\r\n"
			+ "Find shortest word in sentence.\r\n"
			+ "\r\n"
			+ "Check if string contains only digits.\r\n"
			+ "\r\n"
			+ "Count frequency of characters.\r\n"
			+ "\r\n"
			+ "Remove all vowels from string.\r\n"
			+ "\r\n"
			+ "Print all permutations of a string.\r\n"
			+ "\r\n"
			+ "Find duplicate characters in string.\r\n"
			+ "\r\n"
			+ "Reverse words in a sentence.\r\n"
			+ "\r\n"
			+ "Find longest substring without repeating characters.\r\n"
			+ "\r\n"
			+ "Check rotation of string.\r\n"
			+ "\r\n"
			+ "Find common characters between two strings.\r\n"
			+ "\r\n"
			+ "Compress a string (aabcc → a2b1c2).\r\n"
			+ "\r\n"
			+ "Print all substrings.\r\n"
			+ "\r\n"
			+ "Check if string contains another substring.\r\n"
			+ "\r\n"
			+ "Remove a given character.\r\n"
			+ "\r\n"
			+ "Capitalize first letter of each word.\r\n"
			+ "\r\n"
			+ "Find ASCII difference between characters.\r\n"
			+ "\r\n"
			+ "Find longest palindrome substring.\r\n"
			+ "\r\n"
			+ "Count uppercase letters.\r\n"
			+ "\r\n"
			+ "Count lowercase letters.\r\n"
			+ "\r\n"
			+ "Toggle case of characters.\r\n"
			+ "\r\n"
			+ "Sort characters in string.\r\n"
			+ "\r\n"
			+ "Reverse string without using reverse() method.\r\n"
			+ "\r\n"
			+ "Check balanced parentheses in string.\r\n"
			+ "\r\n"
			+ "Find repeating substrings.\r\n"
			+ "\r\n"
			+ "Find smallest window containing characters.\r\n"
			+ "\r\n"
			+ "Check valid shuffle of two strings.\r\n"
			+ "\r\n"
			+ "Find longest common prefix.\r\n"
			+ "\r\n"
			+ "4. Array Problems (81–120)\r\n"
			+ "\r\n"
			+ "Find largest element in array.\r\n"
			+ "\r\n"
			+ "Find smallest element in array.\r\n"
			+ "\r\n"
			+ "Find second largest element.\r\n"
			+ "\r\n"
			+ "Reverse an array.\r\n"
			+ "\r\n"
			+ "Find sum of array elements.\r\n"
			+ "\r\n"
			+ "Find average of array.\r\n"
			+ "\r\n"
			+ "Remove duplicates from array.\r\n"
			+ "\r\n"
			+ "Find missing number in array.\r\n"
			+ "\r\n"
			+ "Move zeros to end.\r\n"
			+ "\r\n"
			+ "Sort array using bubble sort.\r\n"
			+ "\r\n"
			+ "Sort array using selection sort.\r\n"
			+ "\r\n"
			+ "Sort array using insertion sort.\r\n"
			+ "\r\n"
			+ "Find intersection of two arrays.\r\n"
			+ "\r\n"
			+ "Find union of two arrays.\r\n"
			+ "\r\n"
			+ "Rotate array left.\r\n"
			+ "\r\n"
			+ "Rotate array right.\r\n"
			+ "\r\n"
			+ "Find pair with given sum.\r\n"
			+ "\r\n"
			+ "Find duplicate number.\r\n"
			+ "\r\n"
			+ "Find majority element.\r\n"
			+ "\r\n"
			+ "Find maximum subarray sum.\r\n"
			+ "\r\n"
			+ "Merge two sorted arrays.\r\n"
			+ "\r\n"
			+ "Find kth largest element.\r\n"
			+ "\r\n"
			+ "Count frequency of elements.\r\n"
			+ "\r\n"
			+ "Find equilibrium index.\r\n"
			+ "\r\n"
			+ "Rearrange positive and negative numbers.\r\n"
			+ "\r\n"
			+ "Find leaders in array.\r\n"
			+ "\r\n"
			+ "Find triplet with given sum.\r\n"
			+ "\r\n"
			+ "Find subarray with given sum.\r\n"
			+ "\r\n"
			+ "Find longest consecutive sequence.\r\n"
			+ "\r\n"
			+ "Find product of array except self.\r\n"
			+ "\r\n"
			+ "Find repeating and missing number.\r\n"
			+ "\r\n"
			+ "Find peak element.\r\n"
			+ "\r\n"
			+ "Check if array is sorted.\r\n"
			+ "\r\n"
			+ "Remove element from array.\r\n"
			+ "\r\n"
			+ "Replace each element with next greater.\r\n"
			+ "\r\n"
			+ "Count inversions in array.\r\n"
			+ "\r\n"
			+ "Find minimum difference pair.\r\n"
			+ "\r\n"
			+ "Rearrange array alternatively.\r\n"
			+ "\r\n"
			+ "Find max product pair.\r\n"
			+ "\r\n"
			+ "Convert array to zigzag.\r\n"
			+ "\r\n"
			+ "5. Recursion (121–140)\r\n"
			+ "\r\n"
			+ "Factorial using recursion.\r\n"
			+ "\r\n"
			+ "Fibonacci using recursion.\r\n"
			+ "\r\n"
			+ "Sum of N numbers using recursion.\r\n"
			+ "\r\n"
			+ "Reverse string using recursion.\r\n"
			+ "\r\n"
			+ "Power calculation using recursion.\r\n"
			+ "\r\n"
			+ "Print numbers from N to 1.\r\n"
			+ "\r\n"
			+ "Print numbers from 1 to N.\r\n"
			+ "\r\n"
			+ "Check palindrome using recursion.\r\n"
			+ "\r\n"
			+ "Binary search using recursion.\r\n"
			+ "\r\n"
			+ "Tower of Hanoi.\r\n"
			+ "\r\n"
			+ "Generate all subsets.\r\n"
			+ "\r\n"
			+ "Generate permutations.\r\n"
			+ "\r\n"
			+ "Count ways to climb stairs.\r\n"
			+ "\r\n"
			+ "Recursive GCD.\r\n"
			+ "\r\n"
			+ "Recursive LCM.\r\n"
			+ "\r\n"
			+ "Print array elements recursively.\r\n"
			+ "\r\n"
			+ "Sum of digits recursively.\r\n"
			+ "\r\n"
			+ "Reverse number recursively.\r\n"
			+ "\r\n"
			+ "Check sorted array recursively.\r\n"
			+ "\r\n"
			+ "Find maximum element recursively.\r\n"
			+ "\r\n"
			+ "6. Searching Algorithms (141–150)\r\n"
			+ "\r\n"
			+ "Linear search implementation.\r\n"
			+ "\r\n"
			+ "Binary search implementation.\r\n"
			+ "\r\n"
			+ "Recursive binary search.\r\n"
			+ "\r\n"
			+ "Find first occurrence using binary search.\r\n"
			+ "\r\n"
			+ "Find last occurrence using binary search.\r\n"
			+ "\r\n"
			+ "Count occurrences of element.\r\n"
			+ "\r\n"
			+ "Find floor of element.\r\n"
			+ "\r\n"
			+ "Find ceil of element.\r\n"
			+ "\r\n"
			+ "Search in rotated sorted array.\r\n"
			+ "\r\n"
			+ "Find square root using binary search.\r\n"
			+ "\r\n"
			+ "7. Sorting Algorithms (151–170)\r\n"
			+ "\r\n"
			+ "Bubble sort.\r\n"
			+ "\r\n"
			+ "Selection sort.\r\n"
			+ "\r\n"
			+ "Insertion sort.\r\n"
			+ "\r\n"
			+ "Merge sort.\r\n"
			+ "\r\n"
			+ "Quick sort.\r\n"
			+ "\r\n"
			+ "Heap sort.\r\n"
			+ "\r\n"
			+ "Counting sort.\r\n"
			+ "\r\n"
			+ "Radix sort.\r\n"
			+ "\r\n"
			+ "Bucket sort.\r\n"
			+ "\r\n"
			+ "Shell sort.\r\n"
			+ "\r\n"
			+ "Sort array of 0s,1s,2s.\r\n"
			+ "\r\n"
			+ "Sort nearly sorted array.\r\n"
			+ "\r\n"
			+ "Find kth smallest element.\r\n"
			+ "\r\n"
			+ "Sort strings alphabetically.\r\n"
			+ "\r\n"
			+ "Sort characters in string.\r\n"
			+ "\r\n"
			+ "Sort map by value.\r\n"
			+ "\r\n"
			+ "Sort custom objects.\r\n"
			+ "\r\n"
			+ "External sorting concept implementation.\r\n"
			+ "\r\n"
			+ "Sort linked list.\r\n"
			+ "\r\n"
			+ "Stable vs unstable sorting example.\r\n"
			+ "\r\n"
			+ "8. Hashing / HashMap (171–190)\r\n"
			+ "\r\n"
			+ "Count frequency using HashMap.\r\n"
			+ "\r\n"
			+ "Find first non-repeating element.\r\n"
			+ "\r\n"
			+ "Find duplicates using HashSet.\r\n"
			+ "\r\n"
			+ "Check subset using HashSet.\r\n"
			+ "\r\n"
			+ "Two sum problem using HashMap.\r\n"
			+ "\r\n"
			+ "Longest consecutive sequence using HashSet.\r\n"
			+ "\r\n"
			+ "Group anagrams using HashMap.\r\n"
			+ "\r\n"
			+ "Find intersection using HashSet.\r\n"
			+ "\r\n"
			+ "Implement custom HashMap.\r\n"
			+ "\r\n"
			+ "Find pairs with given difference.\r\n"
			+ "\r\n"
			+ "Count distinct elements.\r\n"
			+ "\r\n"
			+ "Find zero sum subarray.\r\n"
			+ "\r\n"
			+ "Longest subarray with equal 0 and 1.\r\n"
			+ "\r\n"
			+ "Check if array contains duplicates within k distance.\r\n"
			+ "\r\n"
			+ "Find itinerary from tickets.\r\n"
			+ "\r\n"
			+ "Count subarrays with given sum.\r\n"
			+ "\r\n"
			+ "Find longest subarray divisible by k.\r\n"
			+ "\r\n"
			+ "Find top k frequent elements.\r\n"
			+ "\r\n"
			+ "Implement LRU cache using HashMap.\r\n"
			+ "\r\n"
			+ "Check symmetric pairs.\r\n"
			+ "\r\n"
			+ "9. Linked List (191–210)\r\n"
			+ "\r\n"
			+ "Create singly linked list.\r\n"
			+ "\r\n"
			+ "Insert node at beginning.\r\n"
			+ "\r\n"
			+ "Insert node at end.\r\n"
			+ "\r\n"
			+ "Delete node from list.\r\n"
			+ "\r\n"
			+ "Reverse linked list.\r\n"
			+ "\r\n"
			+ "Find middle element.\r\n"
			+ "\r\n"
			+ "Detect loop in linked list.\r\n"
			+ "\r\n"
			+ "Remove loop.\r\n"
			+ "\r\n"
			+ "Find nth node from end.\r\n"
			+ "\r\n"
			+ "Merge two sorted lists.\r\n"
			+ "\r\n"
			+ "Remove duplicates from list.\r\n"
			+ "\r\n"
			+ "Find intersection point.\r\n"
			+ "\r\n"
			+ "Reverse in groups of k.\r\n"
			+ "\r\n"
			+ "Check palindrome linked list.\r\n"
			+ "\r\n"
			+ "Delete without head pointer.\r\n"
			+ "\r\n"
			+ "Flatten linked list.\r\n"
			+ "\r\n"
			+ "Rotate linked list.\r\n"
			+ "\r\n"
			+ "Add two numbers represented by linked lists.\r\n"
			+ "\r\n"
			+ "Sort linked list.\r\n"
			+ "\r\n"
			+ "Clone linked list with random pointer.\r\n"
			+ "\r\n"
			+ "10. Stack (211–225)\r\n"
			+ "\r\n"
			+ "Implement stack using array.\r\n"
			+ "\r\n"
			+ "Implement stack using linked list.\r\n"
			+ "\r\n"
			+ "Reverse stack using recursion.\r\n"
			+ "\r\n"
			+ "Check balanced parentheses.\r\n"
			+ "\r\n"
			+ "Implement min stack.\r\n"
			+ "\r\n"
			+ "Evaluate postfix expression.\r\n"
			+ "\r\n"
			+ "Convert infix to postfix.\r\n"
			+ "\r\n"
			+ "Convert postfix to infix.\r\n"
			+ "\r\n"
			+ "Next greater element.\r\n"
			+ "\r\n"
			+ "Stock span problem.\r\n"
			+ "\r\n"
			+ "Largest rectangle in histogram.\r\n"
			+ "\r\n"
			+ "Sort stack using recursion.\r\n"
			+ "\r\n"
			+ "Implement stack using queues.\r\n"
			+ "\r\n"
			+ "Reverse string using stack.\r\n"
			+ "\r\n"
			+ "Celebrity problem using stack.\r\n"
			+ "\r\n"
			+ "11. Queue (226–240)\r\n"
			+ "\r\n"
			+ "Implement queue using array.\r\n"
			+ "\r\n"
			+ "Implement queue using linked list.\r\n"
			+ "\r\n"
			+ "Circular queue implementation.\r\n"
			+ "\r\n"
			+ "Deque implementation.\r\n"
			+ "\r\n"
			+ "Implement queue using stacks.\r\n"
			+ "\r\n"
			+ "Reverse queue.\r\n"
			+ "\r\n"
			+ "Generate binary numbers using queue.\r\n"
			+ "\r\n"
			+ "Sliding window maximum.\r\n"
			+ "\r\n"
			+ "First non repeating character in stream.\r\n"
			+ "\r\n"
			+ "Implement priority queue.\r\n"
			+ "\r\n"
			+ "Queue using two stacks.\r\n"
			+ "\r\n"
			+ "Rotten oranges problem.\r\n"
			+ "\r\n"
			+ "Circular tour petrol pump.\r\n"
			+ "\r\n"
			+ "Interleave queue elements.\r\n"
			+ "\r\n"
			+ "LRU cache using queue.\r\n"
			+ "\r\n"
			+ "12. Trees (241–260)\r\n"
			+ "\r\n"
			+ "Create binary tree.\r\n"
			+ "\r\n"
			+ "Inorder traversal.\r\n"
			+ "\r\n"
			+ "Preorder traversal.\r\n"
			+ "\r\n"
			+ "Postorder traversal.\r\n"
			+ "\r\n"
			+ "Level order traversal.\r\n"
			+ "\r\n"
			+ "Height of binary tree.\r\n"
			+ "\r\n"
			+ "Count nodes in binary tree.\r\n"
			+ "\r\n"
			+ "Count leaf nodes.\r\n"
			+ "\r\n"
			+ "Diameter of tree.\r\n"
			+ "\r\n"
			+ "Check identical trees.\r\n"
			+ "\r\n"
			+ "Check symmetric tree.\r\n"
			+ "\r\n"
			+ "Lowest common ancestor.\r\n"
			+ "\r\n"
			+ "Print left view of tree.\r\n"
			+ "\r\n"
			+ "Print right view of tree.\r\n"
			+ "\r\n"
			+ "Zigzag traversal.\r\n"
			+ "\r\n"
			+ "Boundary traversal.\r\n"
			+ "\r\n"
			+ "Vertical order traversal.\r\n"
			+ "\r\n"
			+ "Top view of tree.\r\n"
			+ "\r\n"
			+ "Bottom view of tree.\r\n"
			+ "\r\n"
			+ "Convert tree to mirror.\r\n"
			+ "\r\n"
			+ "13. Binary Search Tree (261–270)\r\n"
			+ "\r\n"
			+ "Insert node in BST.\r\n"
			+ "\r\n"
			+ "Delete node in BST.\r\n"
			+ "\r\n"
			+ "Search element in BST.\r\n"
			+ "\r\n"
			+ "Validate BST.\r\n"
			+ "\r\n"
			+ "Find kth smallest in BST.\r\n"
			+ "\r\n"
			+ "Find kth largest in BST.\r\n"
			+ "\r\n"
			+ "Convert BST to sorted list.\r\n"
			+ "\r\n"
			+ "Find LCA in BST.\r\n"
			+ "\r\n"
			+ "Balance a BST.\r\n"
			+ "\r\n"
			+ "Range sum of BST.\r\n"
			+ "\r\n"
			+ "14. Heap / Priority Queue (271–280)\r\n"
			+ "\r\n"
			+ "Implement min heap.\r\n"
			+ "\r\n"
			+ "Implement max heap.\r\n"
			+ "\r\n"
			+ "Heapify an array.\r\n"
			+ "\r\n"
			+ "Find kth largest using heap.\r\n"
			+ "\r\n"
			+ "Merge k sorted arrays.\r\n"
			+ "\r\n"
			+ "Find median from data stream.\r\n"
			+ "\r\n"
			+ "Top k frequent elements using heap.\r\n"
			+ "\r\n"
			+ "Connect ropes with minimum cost.\r\n"
			+ "\r\n"
			+ "Reorganize string using heap.\r\n"
			+ "\r\n"
			+ "Sliding window median.\r\n"
			+ "\r\n"
			+ "15. Graph (281–295)\r\n"
			+ "\r\n"
			+ "Graph representation using adjacency list.\r\n"
			+ "\r\n"
			+ "Graph representation using matrix.\r\n"
			+ "\r\n"
			+ "Breadth First Search (BFS).\r\n"
			+ "\r\n"
			+ "Depth First Search (DFS).\r\n"
			+ "\r\n"
			+ "Detect cycle in graph.\r\n"
			+ "\r\n"
			+ "Detect cycle in directed graph.\r\n"
			+ "\r\n"
			+ "Topological sort.\r\n"
			+ "\r\n"
			+ "Dijkstra shortest path.\r\n"
			+ "\r\n"
			+ "Bellman Ford algorithm.\r\n"
			+ "\r\n"
			+ "Floyd Warshall algorithm.\r\n"
			+ "\r\n"
			+ "Minimum spanning tree (Kruskal).\r\n"
			+ "\r\n"
			+ "Minimum spanning tree (Prim).\r\n"
			+ "\r\n"
			+ "Number of islands problem.\r\n"
			+ "\r\n"
			+ "Clone graph.\r\n"
			+ "\r\n"
			+ "Bipartite graph check.\r\n"
			+ "\r\n"
			+ "16. Dynamic Programming (296–300)\r\n"
			+ "\r\n"
			+ "Fibonacci using DP.\r\n"
			+ "\r\n"
			+ "Longest common subsequence.\r\n"
			+ "\r\n"
			+ "Longest increasing subsequence.\r\n"
			+ "\r\n"
			+ "0/1 Knapsack problem.\r\n"
			+ "\r\n"
			+ "Coin change problem.\r\n"
			+ "");
}
	
	
}
